# find()     在字符串中查找子串，返回第一次出现的索引位置，找不到返回-1   s.find('Python')
# count()    统计子串在字符串中出现的次数                           s.count('H')
# upper()    将字符串中的所有字母转换为大写                          s.upper()
# lower()    将字符串中的所有字母转换为小写                          s.lower()
# split()    将字符串按指定分隔符分割成列表                          s.split(' ')
# strip()    去除字符串两端的空白字符或指定字符                  s.strip()/s.strip('*')
# replace()  将字符串中的指定子串替换为新的子串                       s.replace('H','C')
# startswith()/endswith()  检查字符串是否以指定子串开头/结尾，返回布尔值               s.startswith('P')/s.endswith('P')
str1 = ' Hello Python Hello World'
print(str1.find('Python'))
print(str1.count('H'))
print(str1.upper())
print(str1.lower())
print(str1.split(' '))
print(str1.strip())
print(str1.strip('World'))
print(str1.replace('Hello','你好'))
print(str1.startswith(' '))
print(str1.endswith('d'))
 # 其余方法见书91页
