# 方法：方法就像是物品具备的能力或功能
# append()     在列表的尾部追加元素         s.append(10086)
# insert()     在指定索引之前，插入该元素    s.insert(0,10086)
# remove()     移除列表中第一个匹配到的值    s.remove(10086)
# pop()        删除列表中指定索引位置的元素（如果未指定索引，默认删除最后一个）   s.pop(2)/s.pop()
# sort()       对列表进行排序（列表元素的数据类型一致，才可以进行排序）    s.sort()
# reverse()    反转列表元素                s.reverse()
# clear()      清空列表元素                s.clear()
# count        指定元素出现次数             s.count(8)
s = [1,2,3,4,5,8,7,6,9]
s.append(10086)
print(s)
s.insert(0,10086)
print(s)
s.remove(10086)
print(s)
s.pop()
print(s)
s.sort()
print(s)
s.reverse()
print(s)
print(s.count(2))
s.clear()
print(s)